name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch: # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: junaidalam2
          outputs: dist/snake.svg

      - name: Push Snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
